# Generated by Django 3.2.4 on 2021-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
