# Generated by Django 3.2.4 on 2021-11-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='room',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
